2024-11-21 16:00:05,210 [DEBUG] DroneApp has started! Directory ./
2024-11-21 16:00:11,125 [WARNING] Link timeout, no heartbeat in last 5 seconds
2024-11-21 16:00:36,113 [ERROR] Exception in MAVLink input loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/dronekit/mavlink.py", line 211, in mavlink_thread_in
    fn(self)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 1370, in listener
    raise APIException('No heartbeat in %s seconds, aborting.' %
dronekit.APIException: No heartbeat in 30 seconds, aborting.
2024-11-21 16:00:36,160 [ERROR] Timeout in initializing connection.
Traceback (most recent call last):
  File "/home/gourav/raspi-app/app.py", line 74, in <module>
    drone = Drone(config)
  File "/home/gourav/raspi-app/drone.py", line 19, in __init__
    self.vehicle = connect(rpi_ip + ":" + str(sim_port),  baud=57600, wait_ready=True)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 3166, in connect
    vehicle.initialize(rate=rate, heartbeat_timeout=heartbeat_timeout)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 2275, in initialize
    raise APIException('Timeout in initializing connection.')
dronekit.APIException: Timeout in initializing connection.
2024-11-21 16:00:43,198 [WARNING] Link timeout, no heartbeat in last 5 seconds
2024-11-21 16:01:08,190 [ERROR] Exception in MAVLink input loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/dronekit/mavlink.py", line 211, in mavlink_thread_in
    fn(self)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 1370, in listener
    raise APIException('No heartbeat in %s seconds, aborting.' %
dronekit.APIException: No heartbeat in 30 seconds, aborting.
2024-11-21 16:01:08,221 [ERROR] Timeout in initializing connection.
Traceback (most recent call last):
  File "/home/gourav/raspi-app/app.py", line 74, in <module>
    drone = Drone(config)
  File "/home/gourav/raspi-app/drone.py", line 19, in __init__
    self.vehicle = connect(rpi_ip + ":" + str(sim_port),  baud=57600, wait_ready=True)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 3166, in connect
    vehicle.initialize(rate=rate, heartbeat_timeout=heartbeat_timeout)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 2275, in initialize
    raise APIException('Timeout in initializing connection.')
dronekit.APIException: Timeout in initializing connection.
2024-11-21 16:01:15,257 [WARNING] Link timeout, no heartbeat in last 5 seconds
2024-11-21 16:01:40,241 [ERROR] Exception in MAVLink input loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/dronekit/mavlink.py", line 211, in mavlink_thread_in
    fn(self)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 1370, in listener
    raise APIException('No heartbeat in %s seconds, aborting.' %
dronekit.APIException: No heartbeat in 30 seconds, aborting.
2024-11-21 16:01:40,282 [ERROR] Timeout in initializing connection.
Traceback (most recent call last):
  File "/home/gourav/raspi-app/app.py", line 74, in <module>
    drone = Drone(config)
  File "/home/gourav/raspi-app/drone.py", line 19, in __init__
    self.vehicle = connect(rpi_ip + ":" + str(sim_port),  baud=57600, wait_ready=True)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 3166, in connect
    vehicle.initialize(rate=rate, heartbeat_timeout=heartbeat_timeout)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 2275, in initialize
    raise APIException('Timeout in initializing connection.')
dronekit.APIException: Timeout in initializing connection.
2024-11-21 16:01:47,316 [WARNING] Link timeout, no heartbeat in last 5 seconds
2024-11-21 16:02:12,305 [ERROR] Exception in MAVLink input loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/dronekit/mavlink.py", line 211, in mavlink_thread_in
    fn(self)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 1370, in listener
    raise APIException('No heartbeat in %s seconds, aborting.' %
dronekit.APIException: No heartbeat in 30 seconds, aborting.
2024-11-21 16:02:12,343 [ERROR] Timeout in initializing connection.
Traceback (most recent call last):
  File "/home/gourav/raspi-app/app.py", line 74, in <module>
    drone = Drone(config)
  File "/home/gourav/raspi-app/drone.py", line 19, in __init__
    self.vehicle = connect(rpi_ip + ":" + str(sim_port),  baud=57600, wait_ready=True)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 3166, in connect
    vehicle.initialize(rate=rate, heartbeat_timeout=heartbeat_timeout)
  File "/usr/local/lib/python3.9/dist-packages/dronekit/__init__.py", line 2275, in initialize
    raise APIException('Timeout in initializing connection.')
dronekit.APIException: Timeout in initializing connection.
2024-11-21 16:02:19,379 [WARNING] Link timeout, no heartbeat in last 5 seconds
