2024-11-21 13:11:45,772 [DEBUG] DroneApp has started! Directory ./
2024-11-21 13:11:46,279 [ERROR] 'simulator_ip'
Traceback (most recent call last):
  File "/home/gourav/raspi-app/app.py", line 74, in <module>
    drone = Drone(config)
  File "/home/gourav/raspi-app/drone.py", line 11, in __init__
    simulator_ip = configurations['drone']['simulator_ip']
  File "/usr/lib/python3.9/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'simulator_ip'
2024-11-21 13:11:48,284 [ERROR] 'simulator_ip'
Traceback (most recent call last):
  File "/home/gourav/raspi-app/app.py", line 74, in <module>
    drone = Drone(config)
  File "/home/gourav/raspi-app/drone.py", line 11, in __init__
    simulator_ip = configurations['drone']['simulator_ip']
  File "/usr/lib/python3.9/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'simulator_ip'
2024-11-21 13:11:50,286 [ERROR] 'simulator_ip'
Traceback (most recent call last):
  File "/home/gourav/raspi-app/app.py", line 74, in <module>
    drone = Drone(config)
  File "/home/gourav/raspi-app/drone.py", line 11, in __init__
    simulator_ip = configurations['drone']['simulator_ip']
  File "/usr/lib/python3.9/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'simulator_ip'
2024-11-21 13:11:52,290 [ERROR] 'simulator_ip'
Traceback (most recent call last):
  File "/home/gourav/raspi-app/app.py", line 74, in <module>
    drone = Drone(config)
  File "/home/gourav/raspi-app/drone.py", line 11, in __init__
    simulator_ip = configurations['drone']['simulator_ip']
  File "/usr/lib/python3.9/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'simulator_ip'
2024-11-21 13:11:54,294 [ERROR] 'simulator_ip'
Traceback (most recent call last):
  File "/home/gourav/raspi-app/app.py", line 74, in <module>
    drone = Drone(config)
  File "/home/gourav/raspi-app/drone.py", line 11, in __init__
    simulator_ip = configurations['drone']['simulator_ip']
  File "/usr/lib/python3.9/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'simulator_ip'
